version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "::1:53"
    expose:
      - "80"
      - "53"
    environment:
      ipv6: 'true'
      ServerIP: $IP
      ServerIPv6: $IPv6
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.local
      VIRTUAL_PORT: 80
      TZ: 'Europe/Berlin'
      WEBPASSWORD: '$PW'
      DHCP_ACTIVE: 'false'
    volumes:
       - '/opt/containers/pihole/pihole/:/etc/pihole/'
       - '/opt/containers/pihole/dnsmasq/:/etc/dnsmasq.d/'
#    dns:
#      - 127.0.0.1
#      - 1.1.1.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.pihole.rule=Host(`pihole.local`)"
      - "traefik.http.routers.pihole.middlewares=local@file"
    networks:
      web:
      vpn-network:
        ipv4_address: 172.21.0.2

networks:
    web:
      external: true
    vpn-network:
      external: true
