version: '3.8'

services:
  db:
    container_name: phpmyadmin-db
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: hannes
      MYSQL_PASSWORD: mysql
    networks:
      - default
     
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      - "traefik.http.routers.phpmyadmin.rule=Host(`db.local`)"
      - "traefik.http.middlewares.local.ipwhitelist.sourceRange=127.0.0.1/32, 192.168.223.1/24"
      - "traefik.http.routers.phpmyadmin.middlewares=local"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root 
    networks:
      - default
      - web

networks:
  web:
    external: true
